language: go
go:
 - 1.7.x
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x
 - tip

install:
  - go get -t ./
  - go get -t ./stores/...
script: go test -v -cover `go list ./... | grep -v 'examples\|benchmarks'`
